DROP TABLE IF EXISTS `prices`;

CREATE TABLE `prices` (
    `ID` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `PRICE` INTEGER,
    `CODE` CHAR(3)
);

INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (1000, '101');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (2000, '101');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (3000, '201');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (4000, '301');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (5000, '101');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (6000, '201');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (7000, '301');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (8000, '101');
INSERT INTO `prices`(`PRICE`, `CODE`) VALUES (9000, '201');

CREATE TABLE `ex_prices` (
    `PRICE` INTEGER
);

INSERT INTO `ex_prices` VALUES (3000);
INSERT INTO `ex_prices` VALUES (5000);
